apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ose-rs
  namespace: dev
spec:
  selector: 
    matchLabels:
      app: acada-app
  template: 
    metadata:
      name: ose-pod
      labels:
        app: acada-app
    spec: 
      containers:
      - name: ose-c
        image: acadalearning/acada:2.5
        ports:
        - containerPort: 8080
