apiVersion: apps/v1
kind: Deployment
metadata:
  name: ose-rs
  namespace: dev
spec:
  replicas: 7
  selector: 
    matchLabels:
      app: acada-app
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 30
  template: 
    metadata:
      name: ose-pod
      labels:
        app: acada-app
    spec: 
      containers:
      - name: ose-c
        image: acadalearning/acada:2.5
        ports:
        - containerPort: 8080
---

apiVersion: v1 
kind: Service 
metadata:
  name: ose-svc
  namespace: dev
spec: 
  type: NodePort
  selector: 
    app: acada-app
  ports: 
  - targetPort: 8080
    port: 80
    protocol: TCP
    nodePort: 32000
